# Generated by Django 3.0.4 on 2020-03-19 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assassins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assassin',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='assassin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='killfeed',
            name='killedID',
        ),
        migrations.RemoveField(
            model_name='killfeed',
            name='killerID',
        ),
        migrations.AddField(
            model_name='assassin',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killfeed',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='killfeed',
            name='killed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='killed', to='assassins.Assassin'),
        ),
        migrations.AddField(
            model_name='killfeed',
            name='killer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='killer', to='assassins.Assassin'),
        ),
        migrations.AddField(
            model_name='respawn',
            name='assassin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assassins.Assassin'),
        ),
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='Niels', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assassin',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respawn',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
