# Generated by Django 4.2 on 2023-04-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assassins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='killfeed',
            name='hide_kill',
            field=models.BooleanField(default=False),
        ),
    ]
