# Generated by Django 3.0.4 on 2020-03-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assassins', '0005_auto_20200319_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respawn',
            name='nextId',
        ),
        migrations.AddField(
            model_name='respawn',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
