# Generated by Django 3.0.4 on 2020-03-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assassins', '0007_auto_20200319_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killfeed',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
    ]
