# Generated by Django 3.0.7 on 2020-06-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assassins', '0009_auto_20200319_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
