# Generated by Django 3.0.4 on 2020-03-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assassin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=30)),
                ('team', models.IntegerField()),
                ('target', models.IntegerField()),
                ('dead', models.BooleanField()),
            ],
        ),
    ]
